# Numpy

## Crear array

In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6]
arr = np.array(lista)

In [3]:
type(lista)

list

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
lista2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(lista2)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
arr

array([1, 2, 3, 4, 5, 6])

In [11]:
arr[2]

np.int64(3)

In [12]:
print(arr[2] + arr[3])

7


In [13]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
matriz[1, 2]

np.int64(6)

In [15]:
arr[0:3]

array([1, 2, 3])

In [16]:
arr[:3]

array([1, 2, 3])

In [17]:
arr[3:]

array([4, 5, 6])

In [18]:
arr

array([1, 2, 3, 4, 5, 6])

In [19]:
arr[::3]

array([1, 4])

In [20]:
arr[-1]

np.int64(6)

In [21]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [22]:
arr.dtype

dtype('int64')

In [23]:
arr = arr.astype(np.float64)

In [24]:
arr.dtype

dtype('float64')

In [25]:
arr

array([1., 2., 3., 4., 5., 6.])

In [26]:
arr.astype(np.bool_)

array([ True,  True,  True,  True,  True,  True])

In [27]:
arr.astype(np.str_)

array(['1.0', '2.0', '3.0', '4.0', '5.0', '6.0'], dtype='<U32')

In [28]:
arr = np.array(['1', '2', '3', '4'], np.int8)


In [29]:
arr

array([1, 2, 3, 4], dtype=int8)

# Dimensiones

In [30]:
escalar = np.array(42)

In [31]:
type(escalar)

numpy.ndarray

In [32]:
escalar.ndim

0

In [33]:
vector = np.array([1, 2, 3])

In [34]:
vector.ndim

1

In [35]:
matriz = np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]])

In [36]:
matriz.ndim

2

In [37]:
tensor = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15],[16, 17, 18]]])

In [38]:
tensor.ndim

3

In [39]:
vector = np.array([1, 2, 3], ndmin=10)

In [40]:
vector

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [41]:
vector.ndim

10

In [42]:
a = np.array([1, 2, 3])

In [43]:
a[1]

np.int64(2)

In [44]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)

[[1 2 3]]


In [45]:
expand[0, 1]

np.int64(2)

In [46]:
expand2 = np.expand_dims(np.array([1, 2, 3]), axis=1)
print(expand2)

[[1]
 [2]
 [3]]


In [47]:
expand2[1,0]

np.int64(2)

In [48]:
vector_2 = np.squeeze(expand)

In [49]:
vector_2.ndim

1

In [50]:
expand.ndim

2

In [51]:
vector_3 = np.squeeze(expand2)

In [52]:
vector_3.ndim

1

In [53]:
m = np.array([1, 2, 3, 4])

In [54]:
my_list = list (range(0, 10))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
m = np.arange(0, 10)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [59]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [61]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
np.random.rand()

0.31434081450358886

In [63]:
np.random.rand(4)

array([0.04755586, 0.21928916, 0.37599093, 0.90368329])

In [64]:
np.random.random((3,4))

array([[0.76197832, 0.53161159, 0.44151782, 0.90668118],
       [0.93938594, 0.83032016, 0.65366212, 0.4449756 ],
       [0.22246744, 0.94194279, 0.43274313, 0.80458366]])

In [65]:
np.random.randint(1, 6)

2

In [66]:
np.random.randint(1, 6, (10, 10))

array([[3, 4, 5, 2, 4, 3, 5, 4, 2, 1],
       [4, 1, 4, 3, 3, 4, 2, 4, 1, 1],
       [5, 5, 2, 5, 5, 5, 5, 5, 5, 3],
       [3, 3, 3, 3, 3, 4, 2, 2, 3, 4],
       [5, 1, 2, 1, 1, 4, 2, 5, 4, 3],
       [1, 4, 2, 3, 2, 3, 1, 5, 3, 5],
       [4, 4, 2, 1, 4, 2, 1, 4, 4, 1],
       [4, 4, 2, 5, 4, 4, 5, 4, 3, 1],
       [5, 3, 5, 1, 2, 1, 3, 2, 1, 3],
       [2, 4, 1, 2, 5, 4, 1, 1, 2, 5]], dtype=int32)

# Shape y reshape 

In [67]:
arr = np.random.randint(1, 10, (3,2))

In [68]:
arr

array([[5, 6],
       [7, 8],
       [5, 7]], dtype=int32)

In [69]:
arr.shape

(3, 2)

In [70]:
arr = arr.reshape(1, 6)

In [71]:
arr

array([[5, 6, 7, 8, 5, 7]], dtype=int32)

In [72]:
arr = np.reshape(arr, (1, 6))

In [73]:
arr

array([[5, 6, 7, 8, 5, 7]], dtype=int32)

In [74]:
arr = np.random.randint(1, 10, (3,2))
arr

array([[4, 7],
       [3, 5],
       [1, 6]], dtype=int32)

In [75]:
np.reshape(arr, (2,3), 'C')

array([[4, 7, 3],
       [5, 1, 6]], dtype=int32)

In [76]:
np.reshape(arr, (2,3), 'F')

array([[4, 1, 5],
       [3, 7, 6]], dtype=int32)

In [77]:
arr

array([[4, 7],
       [3, 5],
       [1, 6]], dtype=int32)

In [78]:
np.reshape(arr, (2,3), 'A')

array([[4, 7, 3],
       [5, 1, 6]], dtype=int32)

# Funciones

In [79]:
arr = np.random.randint(1, 20, 10)

In [80]:
arr

array([ 6, 10, 13, 10, 11,  8,  8, 12, 11, 19], dtype=int32)

In [81]:
matriz = arr.reshape(2, 5)
matriz

array([[ 6, 10, 13, 10, 11],
       [ 8,  8, 12, 11, 19]], dtype=int32)

In [82]:
arr.max()

np.int32(19)

In [83]:
matriz.max(axis=0)

array([ 8, 10, 13, 11, 19], dtype=int32)

In [84]:
arr.argmax()

np.int64(9)

In [85]:
matriz

array([[ 6, 10, 13, 10, 11],
       [ 8,  8, 12, 11, 19]], dtype=int32)

In [86]:
matriz.argmax()

np.int64(9)

In [87]:
indx = np.unravel_index(np.argmax(matriz), matriz.shape)
print(indx)

(np.int64(1), np.int64(4))


In [88]:
matriz[indx]

np.int32(19)

In [89]:
arr.min()

np.int32(6)

In [90]:
matriz.min(axis=1)

array([6, 8], dtype=int32)

In [91]:
matriz.min()

np.int32(6)

In [92]:
arr.sort()
arr

array([ 6,  8,  8, 10, 10, 11, 11, 12, 13, 19], dtype=int32)

In [93]:
np.percentile(arr, 100)

np.float64(19.0)

In [94]:
np.median(arr)

np.float64(10.5)

In [95]:
np.mean(arr)

np.float64(10.8)

In [96]:
matriz

array([[ 6,  8,  8, 10, 10],
       [11, 11, 12, 13, 19]], dtype=int32)

In [97]:
np.median(matriz, axis=1)

array([ 8., 12.])

In [98]:
np.std(arr)

np.float64(3.370459909270543)

In [99]:
np.var(arr)

np.float64(11.36)

In [100]:
np.std(arr)**2

np.float64(11.359999999999998)

In [101]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

In [102]:
b = np.expand_dims(b, axis = 0)
b

array([[5, 6]])

In [103]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [104]:
b = np.array([5, 6])
b

array([5, 6])

In [105]:
b = np.expand_dims(b, axis = 1)
b

array([[5],
       [6]])

In [106]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [107]:
a.ndim

2

In [108]:
b.ndim

2

# Copy

In [109]:
arr1 = np.arange(0, 11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
arr2 = arr1
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr2[2]= 100
arr2

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [112]:
arr1

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [113]:
arr3 = arr1.copy()
arr3

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [114]:
arr3[2] = 2
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr1

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [117]:
arr4 = arr1[:]

In [120]:
arr4[:] = 0
arr4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Condicionales

In [121]:
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [122]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [123]:
idx_condicion = arr > 5
idx_condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [124]:
arr[idx_condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [125]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [127]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [128]:
arr[(arr > 5) & (arr < 9)] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99,  9, 10], dtype=int8)

# operaciones

In [129]:
l = [1, 2]
l

[1, 2]

In [130]:
l * 2

[1, 2, 1, 2]

In [131]:
arr = np.arange(0, 10)
arr2 = arr.copy()

In [132]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [134]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [135]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [136]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [137]:
arr + arr2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [138]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [139]:
matriz = arr.reshape(2, 5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [140]:
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [141]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [142]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [144]:
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [145]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [146]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [147]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

In [148]:
matriz.dot(matriz2.T)

array([[ 30,  80],
       [ 80, 255]])